export const PLAYWRIGHT_TOOL_NAME = 'Playwright'

export const PLAYWRIGHT_DESCRIPTION = `
- Uses the desktop app's managed Playwright Chromium to perform the exact public-web browser actions supplied in actions, in order
- Actions are visible to the user by default. The supported surface includes navigation/history, tabs, form interaction, keyboard/mouse actions, selectors and waits, DOM inspection, scrolling, screenshots, and returned action traces. For any official Playwright API not represented by a named action, use one {"type":"script","script":"..."} action.
- This tool is a generic browser operator, not a research, SEO, or source-ranking tool. Decide what to search, which links matter, and what evidence supports a conclusion in the active Skill or user instructions
- The script action receives official Playwright-shaped page, context, browser, pages(), and a playwright namespace containing chromium, firefox, webkit, devices, selectors, and request. Use normal page methods, context.newPage(), page.waitForEvent('popup'), or playwright.request.newContext(). In a shared Expert browser, context.pages(), browser.contexts()[0].pages(), and pages() expose only the current Agent's pages; global BrowserContext page events and shared lifecycle methods are blocked so one Agent cannot adopt or close a sibling tab. Cookies and verification state still remain shared
- If a page shows login, CAPTCHA, robots, 403/429, or a regional restriction, record the returned URL and limitation. Do not treat it as evidence and do not attempt to bypass it
- Consecutive Playwright calls in the same chat/session keep the same managed Chromium page. On an unfamiliar or changing page, use two calls: first navigate and extract (or run a script that lists visible editable controls); inspect the returned page state, then fill/type/press only a selector that is actually present. Do not queue navigate, fill, and press with a guessed selector in one first call, and do not start over at about:blank
- For web navigation, filling, clicking, key presses, scrolling, reading, and screenshots on pages already opened by Playwright, continue using Playwright. Do not switch to mcp__computer-use__*, Bash, PowerShell, npx playwright, or a homemade browser script merely to click the page
- Always pass one "actions" array. First inspection example JSON: {"actions":[{"type":"navigate","url":"https://www.baidu.com/"},{"type":"extract","selector":"body"}],"visible":true}. Follow-up search example JSON: {"actions":[{"type":"type","selector":"#kw","text":"productivity software","delay_ms":40},{"type":"press","selector":"#kw","key":"Enter"},{"type":"wait_for_selector","selector":"body","state":"visible"},{"type":"extract","selector":"body"}],"visible":true}. Raw API example: {"actions":[{"type":"script","script":"const tab = await context.newPage(); await tab.goto('https://example.com/'); return { title: await tab.title(), links: await tab.locator('a').count() }"}],"visible":true}. Never send top-level "action" or "url" fields.
`

export function getPlaywrightPrompt(): string { return PLAYWRIGHT_DESCRIPTION }
