/** Shared report-only guidance. No research gate, quota, or new model turn. */
export const REPORT_EVIDENCE_HANDOFF_GUIDANCE = [
  'Keep acquisition and final selection separate: obtained and used, obtained but not used, partially obtained, not obtained, and access-limited are different states. Absence from SOURCE_ROWS never proves absence of evidence. A readable video description with unavailable comments is partial evidence, not an inaccessible platform. Use the exact page/attempt from 06 to bound the observation; do not overwrite a successful observation with a different failed route.',
  'Retain reviewer-approved, decision-relevant details in their matching chapters; repeated or irrelevant material need not be included. Keep every concrete page actually used with its complete audited URL or audit ID. Prefer a distinct label for each page and reuse it in the prose and source table. Do not replace several posts/comments with one representative URL, or a search URL with its homepage. Ordinary Markdown definitions, inline links and explicit source-table labels remain valid; none is a mandatory format.',
  'Separate observed commercial practice from demonstrated commercial outcomes: a public price/free tier proves an offer exists, not conversion, profitability or paid willingness. One competitor allowing free commercial use does not prove commercial licensing impossible for the whole category. Keep useful AI inference with its basis and falsification conditions rather than converting it into a proven conclusion or deleting it.',
  'Correct only the affected report fields or source rows using the existing materials and existing review/patch step. Do not add browsing, agents, review rounds, word/source quotas, or a new completion gate.',
].join('\n')

export const REPORT_ABSORPTION_WORK_GUIDANCE = [
  'Read the brief and independent review to EOF first. D has already reviewed all registered research parts: use its include/merge/partially_verified detail clusters as the primary material, not a second exhaustive pass over every raw shard. Consult only relevant ranges of the declared browser audit or research parts when an exact URL, supporting detail, or status conflict needs checking. Do not scan directories or browse.',
  'Save substantive chapter-ready details and their source identities before further optional lookups; a header, outline or promise to append is not the material package. Use only Read and Write, never instruct this worker to Edit or shell-append. Write overwrites the file: when saving incrementally, include the full accumulated material, then Read back the saved details and references. A non-empty scaffold or a compaction summary is not a completed 07 handoff.',
].join('\n')
