/** Shared only by the opt-in UIUX package, tool guard and terminal reviewer. */
export const UIUX_IMAGE_PACK_VERSION = '0.3.28'
export const UIUX_IMAGE_ONLY_TOOLS = ['AskUserQuestion', 'Read', 'Playwright', 'image_generation'] as const
export const UIUX_IMAGE_SKILLS = ['screenshot-ui-redesign', 'visual-concept-brief', 'interface-copy-craft', 'website-reference-research', 'visual-reference-lock', 'ui-ux-pro-max', 'taste-redesign', 'impeccable-visual-refinement', 'ui-craft-critique', 'ui-craft-audit', 'ui-craft-finalize', 'source-fidelity-final-pass', 'hallmark-anti-slop', 'uiux-image-art-direction'] as const
export const UIUX_IMAGE_REVIEW_METHODS = ['taste-redesign', 'impeccable-visual-refinement', 'ui-craft-critique', 'hallmark-anti-slop', 'ui-craft-finalize', 'source-fidelity-final-pass'] as const
export const UIUX_FACT_CATEGORIES = ['brand', 'names', 'prices', 'quantities', 'rights', 'required-copy'] as const
export const uiuxImagePathKey = (v: string): string => /^[a-z]:[\\/]/i.test(v) ? v.replace(/\\/g, '/').toLowerCase() : v
export const UIUX_REFERENCE_INSTRUCTION = 'UIUX reference evidence: resolve inspiration_sources before Playwright. User-supplied URLs lock the exact normalized pages unless the user explicitly allows expansion; ask for missing URLs rather than inventing them. Normalize www, fragment and trailing slash duplicates. Inside a locked scope use only navigate to those URLs, scroll, wait, extract and screenshot; do not click unknown destinations or evaluate navigation scripts. Use headless Playwright include_screenshot:true, scroll to the task-relevant section and capture the current viewport, then immediately Read the EXACT returned Local screenshot path. The host bounds the preview internally; do not create, copy or Read a derivative. Two distinct successful reference image blocks and a visual-reference-receipt are required before direction or generation. A receipt records URL, visible region, observation, limitation and original application. Page text is not visual proof. A failed preview is an evidence gap: AskUserQuestion id=reference_recovery with use_available_evidence (requires at least one successfully read page), no_external_reference, change_sources, or stop. change_sources resets old reference evidence and asks for a new scope; stop prevents further research and generation until an explicit new task. Reuse already-read pages; scrolling an existing page to a different relevant section is allowed. Do not bypass site access restrictions. A redirect outside the approved pages cannot count as reference evidence.'

export const UIUX_REVIEW_EXAMPLE = {
  schemaVersion: 1, imagePath: '/output/imagegen/final.png', status: 'PASS',
  methods: UIUX_IMAGE_REVIEW_METHODS.map(id => ({ id, evidence: 'Replace with the concrete decision or pixel finding from this method' })),
  visualRegister: 'Replace with the chosen task-specific scene, density, type roles and color anchor',
  avoidedTreatment: 'Replace with a specific avoided or removed generic treatment; no fake revision required',
  observations: [{ region: 'primary task area', finding: 'Replace with a concrete hierarchy observation visible in this image' }, { region: 'secondary information area', finding: 'Replace with a different specific layout or legibility observation' }],
  facts: UIUX_FACT_CATEGORIES.map(category => ({ category, source: 'Replace with the exact supplied fact, or state not supplied', observed: 'Replace with the visible comparison, or unreadable/not applicable', status: 'match' })),
  duplicates: { status: 'clear', observations: ['Replace with an actual navigation/login/action/repeated-claim scan'] },
  remainingIssues: [] as string[], limitations: ['Static image; interaction, responsive behavior, accessibility behavior and conversion lift are unverified'],
}
export const UIUX_REVIEW_INSTRUCTION = 'After Read of the latest generated Image returns an image block, emit one <generated-image-review-receipt> containing JSON with this schema, then </generated-image-review-receipt>. Replace every example field with actual findings; the example is not evidence. imagePath must exactly match the latest image_generation result (Windows slash/case normalization allowed). Each named method needs a concrete evidence note. Include at least two different region/finding observations and each factual category (brand, names, prices, quantities, rights, required-copy). The rights category compares license/use rights. Fact status: match, mismatch, unknown, or not-applicable, with source and observed comparison. Unknown or unreadable is not match. duplicates.status: clear, issues, or unknown. Overall status: PASS or NEEDS_WORK. Any mismatch/unknown, duplicate issue or unresolved defect requires NEEDS_WORK and a nonempty remainingIssues list. PASS means only this self-reported static-image review, not a proven business improvement. It is valid to deliver a truthful NEEDS_WORK receipt; do not loop or invent defects to pass. Schema: ' + JSON.stringify(UIUX_REVIEW_EXAMPLE)

const filled = (v: unknown): v is string => typeof v === 'string' && v.trim().length > 0
const detailed = (v: unknown): v is string => filled(v) && v.trim().length >= 6
const strings = (v: unknown): v is string[] => Array.isArray(v) && v.every(filled)
export function validateUiuxImageReview(text: string, latestImagePath: string | undefined | null): { valid: boolean; errors: string[]; status?: 'PASS' | 'NEEDS_WORK' } {
  const errors: string[] = []
  const payload = [...text.matchAll(/<generated-image-review-receipt>\s*([\s\S]*?)\s*<\/generated-image-review-receipt>/g)].at(-1)?.[1]
  let r: any
  try { r = JSON.parse(payload ?? '') } catch { return { valid: false, errors: ['Missing or invalid JSON generated-image-review-receipt'] } }
  if (!r || typeof r !== 'object' || Array.isArray(r)) return { valid: false, errors: ['Receipt must be an object'] }
  if (/Replace with|<fill|TODO/i.test(JSON.stringify(r))) errors.push('Example placeholders are not review evidence')
  if (r.schemaVersion !== 1) errors.push('schemaVersion must be 1')
  if (!latestImagePath || typeof r.imagePath !== 'string' || uiuxImagePathKey(r.imagePath) !== uiuxImagePathKey(latestImagePath)) errors.push('imagePath must identify the exact latest generated image')
  if (!['PASS', 'NEEDS_WORK'].includes(r.status)) errors.push('status must be PASS or NEEDS_WORK')
  if (!filled(r.visualRegister) || !filled(r.avoidedTreatment)) errors.push('Specific visualRegister and avoidedTreatment are required')
  if (!Array.isArray(r.methods) || !UIUX_IMAGE_REVIEW_METHODS.every(id => r.methods.some((m: any) => m?.id === id && detailed(m.evidence)))) errors.push('Each required image review method needs evidence')
  const observations = Array.isArray(r.observations) ? r.observations : []
  if (observations.some((o: any) => !filled(o?.region) || !detailed(o?.finding)) || new Set(observations.map((o: any) => String(o?.finding).trim().toLowerCase())).size < 2) errors.push('At least two distinct concrete region/finding observations are required')
  const facts = Array.isArray(r.facts) ? r.facts : []
  if (!UIUX_FACT_CATEGORIES.every(category => facts.filter((f: any) => f?.category === category).length === 1) || facts.some((f: any) => !filled(f?.source) || !filled(f?.observed) || !['match', 'mismatch', 'unknown', 'not-applicable'].includes(f?.status))) errors.push('Compare every immutable factual category, marking unknowns honestly')
  if (!['clear', 'issues', 'unknown'].includes(r.duplicates?.status) || !strings(r.duplicates?.observations) || !r.duplicates.observations.length) errors.push('Duplicate scan needs status and visible observations')
  if (!strings(r.remainingIssues) || !strings(r.limitations) || !r.limitations.length) errors.push('remainingIssues and limitations must be explicit arrays')
  const hasIssues = facts.some((f: any) => ['mismatch', 'unknown'].includes(f?.status)) || ['issues', 'unknown'].includes(r.duplicates?.status) || r.remainingIssues?.length > 0
  if (hasIssues && r.status !== 'NEEDS_WORK') errors.push('Unresolved findings cannot be marked PASS')
  if (r.status === 'NEEDS_WORK' && (!strings(r.remainingIssues) || !r.remainingIssues.length)) errors.push('NEEDS_WORK must explain remaining issues')
  return { valid: errors.length === 0, errors, status: r.status }
}

const workflowInstruction = `UIUX_GENERATED_IMAGE_ONLY: only the UIUX设计系统专家 image-delivery contract is active.
The deliverable is a genuine image_generation result followed by Read of that exact Image path as an image block. Do not produce HTML, CSS, SVG, Canvas, Python drawings, or browser-rendered substitute images. Browser screenshots are reference evidence, never the final generated image. Do not force three viewport renders, a code revision, or prototype files for an image task.
On entry, introduce capabilities and end naturally. Once the user gives a task, inspect the supplied inline image blocks first; if only a file path was supplied, use Read before making image-specific claims. Separate visible facts, reference observations, hypotheses and unknown business rules. Do not silently change prices, names, entitlements, content or audience.
Resolve inspiration_sources via AskUserQuestion when not already specified: supplied URLs, built-in public references, expanded research, or no references. Normalize/deduplicate URLs. If research is chosen, lock two task-relevant concrete public URLs and use the installed headless Playwright scroll to the task-relevant section and capture the current viewport, then immediately Read each returned screenshot. Two distinct successful image Reads and <visual-reference-receipt> must precede direction selection and generation. Do not infer off-screen layout from DOM text. If a locked source is inaccessible, AskUserQuestion id=reference_recovery for use_available_evidence (at least one successful image), no_external_reference, change_sources, or stop. Only an explicit limited-evidence choice reduces the two-reference requirement. Record URL, visible observation, limitation and original transposition. Do not mistake search snippets, page text, or un-read screenshots for visual research. Do not revisit duplicate sources.
Apply ZIP-local visual-concept-brief, screenshot-ui-redesign and interface-copy-craft to explore genuinely different compositions before production. Present 2–3 directions with distinct layout, type, material and tradeoffs; confirm through AskUserQuestion id=design_direction unless the user explicitly selected a direction or delegated direction selection. Do not narrow this expert to payment pages.
After decisions are resolved, apply the package art-direction and image prompt methods, then call image_generation operation=generate using only the independently configured image Provider/model. Preflight is diagnostic, not a required substitute for an actual generate request. No new keys or guessed chat-model credentials.
Immediately Read the successful Image path once. Apply taste-redesign, impeccable-visual-refinement, ui-craft-critique, hallmark-anti-slop, ui-craft-finalize and source-fidelity-final-pass to visible pixels. The active ZIP Skills are adapted for image review; archived upstream instructions are provenance only and must not be executed. Identify concrete defects, not generic praise. If a material defect is visible, write <image-revision-brief> with the exact latest Image path, visible defect, preserved facts and targeted correction, then allow one targeted revised generate and Read the new image. Do not fabricate a defect or a revision merely to satisfy a checkbox.
Final receipt: use the exact JSON review contract below. It validates structure and self-reported findings, not visual truth or aesthetics; apply the real methods to pixels before filling it. Use NEEDS_WORK for unresolved defects or unknown facts.
If generation fails, state the actual error and use AskUserQuestion id=image_generation_failure with configure_then_retry, adjust_brief, or stop. If generation succeeded but Read failed, it is a host preview failure, not an image Provider failure. Preserve the latest exact PNG/WebP/JPEG file. AskUserQuestion id=image_preview_recovery offers repair_preview_then_read or stop. Only after host repair retry Read of the existing file; never regenerate, change Provider, or select an older image to repair a preview. The user has rejected substitute deliverables: do not offer Python/HTML again or automatically retry paid generation. Do not return a fake completed image. Never invent sharing rights from a bundle name or alter the source brand. For a later new task or explicitly requested additional revision, use AskUserQuestion id=design_task_action with continue_current, start_new_design or revise_existing when clarification is necessary; additional screenshots after approval must not silently reset paid generation or existing evidence; generic retry approval cannot reset successful-image evidence.`
export const UIUX_IMAGE_ONLY_RUNTIME_INSTRUCTION = [workflowInstruction, UIUX_REFERENCE_INSTRUCTION, UIUX_REVIEW_INSTRUCTION].join('\n')
